### ISSUE TITLE
Add a scroll back to top of the page button 

### ISSUE THREAD

**Issue by bbaqui25** [zeroDevs/coding_challenge-13#122]

**Comment by MattCSmith** [comment]
@bbaqui25 Sounds like a fantastic idea 👍 
Did you want to take this up, or is this up for grabs?

**Comment by bbaqui25** [comment]
I can do it. Since this is my first open source project, I cannot find css file.

**Comment by MattCSmith** [comment]
Perfect!

Since this is a React app, the main portion of the app's code is located in the `src` directory. You are most likely going to want to make the changes to the `App.css` file:
https://github.com/zeroDevs/coding_challenge-13/tree/master/src/App.css

Don't hesitate to shout if you need anything :)

**Comment by bbaqui25** [comment]
Okay, thanks!

**Comment by MattCSmith** [comment]
How is this going @bbaqui25 ?

**Comment by MattCSmith** [comment]
Re-opening as closed in error

@otanriverdi Feel free to take up this issue :)

**Comment by MattCSmith** [comment]
Hey @otanriverdi Are you working on this issue, or should I put it back into the to-do pile?

**Comment by leighd2008** [comment]
I'll take a stab at this one.

**Comment by MattCSmith** [comment]
Closing as implemented in #198
