### ISSUE TITLE
Cross-browser checkbox alignment

### ISSUE THREAD

**Issue by The24thDS** [zeroDevs/coding_challenge-13#153]
The current solution for aligning the checkboxes doesn't work in Edge. Maybe someone can implement a cross-browser one.
![image](https://user-images.githubusercontent.com/26633429/51695171-1032bb00-200b-11e9-8bab-c31a75417a89.png)

**Comment by mortenkos** [comment]
I can do that :)

**Comment by MattCSmith** [comment]
@mortenkos Nice job on fixing this issue, although I have just noticed we have lost the nice formatting for smaller screens.

Instead of looking like this:
![image](https://user-images.githubusercontent.com/6190356/51739212-d3a5a480-2088-11e9-8059-0d1072d74095.png)

It now looks like this:
![image](https://user-images.githubusercontent.com/6190356/51739250-eae49200-2088-11e9-95b3-2acb2b3f320d.png)

Would you be up for tackling this adjustment, or should I put it back into the to-do pile?

**Comment by The24thDS** [comment]
A simple media query should handle that

**Comment by mortenkos** [comment]
I will fix that 😊

**Comment by MattCSmith** [comment]
Closing as this was resolved in #158
