### ISSUE TITLE
Drop Down on mobile Glitch when scroll event is triggered

### ISSUE THREAD

**Issue by AkinAguda** [zeroDevs/coding_challenge-13#157]
When user scrolls down on mobile, and the hamburger icon is clicked, the drop down displays the button the the white background shows later (without transition)

**Comment by The24thDS** [comment]
@allcontributors[bot] add @AkinAguda for bug

**Comment by jakebolam** [comment]
Hey @The24thDS thanks for all the usage on the bot ;) This has been super insightful into helping the community improve the bot. 

The issue you're seeing here is https://github.com/all-contributors/all-contributors-bot/issues/16.

We're working on this one, and should have a fix out soon!

**Comment by luxumbra** [comment]
@jakebolam The bot is a really cool addition.

**Comment by luxumbra** [comment]
I've been looking at this but haven't yet been able to sort it out.

**Comment by MattCSmith** [comment]
@luxumbra I've taken a look at this issue. The issue appears to be because there are two instances of the `collapse.show` css class.

I was able to get the transition to work by moving the `display: block` into the first instance:
![image](https://user-images.githubusercontent.com/6190356/51858175-f3a8c280-232b-11e9-9ed3-0ec061b60bb1.png)

I would also recommend maybe making the background pure white and giving it the var(--one) background. What do you think?
![image](https://user-images.githubusercontent.com/6190356/51858227-20f57080-232c-11e9-9a9e-224e7b934206.png)

**Comment by MattCSmith** [comment]
My comment about making the background pure white., looks like a strange one looking at my screenshot 😆 But looking at it, the navbar seems to change to various shades of white (Depending on scroll), this probably needs fixing

**Comment by MattCSmith** [comment]
Hey @luxumbra, As the deadline is approaching (see #200) Im checking the status of each issue. Are you still thinking of fixing this issue?
Regards
Matt

**Comment by luxumbra** [comment]
Hi @MattCSmith, I would like to fix it. I was planning to work on it this evening but I don't mind if someone else wants to take it on.

The navbar has some transparency which is what I think is giving the effect of changing shades. I'll make it solid white.

**Comment by MattCSmith** [comment]
Hey @luxumbra,
Your good to proceed :) I just wanted to ensure everyone knew about the deadline, so we can push the final thing to producthunt. 

On closer inspection the navbar is transparent, which I kinda like (although I'm happy with solid white too) But when you click the hamburger, it changes to solid white.

So one or the other needs changing I guess :D

**Comment by luxumbra** [comment]
Cool, I'll make it all the same alpha and get on with this shortly.

**Comment by The24thDS** [comment]
Closing as this has been fixed.
